services:
  db:
    image: postgres:bullseye
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: secreto
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
